core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("todo_list.urls", namespace="todo_list")),
]

todo_list/urls.py
from django.urls import path

from .views import (
    TaskListView,
    TaskDetailView,
    TaskCreateView,
    TaskUpdateView,
    TaskDeleteView,
    TagListView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView,
    TaskChangeStatusView,
)

app_name = "todo_list"
urlpatterns = [
    path("", TaskListView.as_view(), name="task-list"),
    path("<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("create/", TaskCreateView.as_view(), name="task-create"),
    path("<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path(
        "change_status/<int:pk>/",
        TaskChangeStatusView.as_view(),
        name="task-change-status",
    ),
    path("tags/", TagListView.as_view(), name="tag-list"),
    path("tags/create/", TagCreateView.as_view(), name="tag-create"),
    path("tags/<int:pk>/update/", TagUpdateView.as_view(), name="tag-update"),
    path("tags/<int:pk>/delete/", TagDeleteView.as_view(), name="tag-delete"),
]

todo_list/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, blank=True, related_name="tasks")

todo_list/forms.py
from django import forms

from todo_list.models import Task

from django.utils import timezone


class TaskForm(forms.ModelForm):

    class Meta:
        model = Task
        fields = ("content", "deadline", "tags")
        widgets = {
            "content": forms.Textarea(attrs={"rows": 3}),
            "deadline": forms.DateInput(
                format="%Y-%m-%d",
                attrs={"placeholder": "Select a date", "type": "date"},
            ),
            "tags": forms.CheckboxSelectMultiple(),
        }

    def clean_deadline(self):
        data = self.cleaned_data.get("deadline")
        if data and data < timezone.now():
            raise forms.ValidationError("Deadline cannot be in the past")
        return data

todo_list/views.py
from django.shortcuts import redirect, reverse
from django.urls import reverse_lazy
from django.views import generic

from todo_list.forms import TaskForm
from todo_list.models import Task, Tag


class TaskListView(generic.ListView):
    model = Task
    queryset = (
        Task.objects.order_by("is_done", "-datetime").prefetch_related("tags")
    )
    paginate_by = 5


class TaskDetailView(generic.DetailView):
    model = Task


class TaskCreateView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("todo_list:task-list")


class TaskUpdateView(generic.UpdateView):
    model = Task
    form_class = TaskForm

    def get_success_url(self):
        return reverse("todo_list:task-detail", kwargs={"pk": self.object.id})


class TaskDeleteView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("todo_list:task-list")


class TaskChangeStatusView(generic.View):
    def get(self, request, *args, **kwargs):
        task = Task.objects.get(id=kwargs["pk"])
        task.is_done = not task.is_done
        task.save()
        return redirect("todo_list:task-list")


class TagListView(generic.ListView):
    model = Tag
    paginate_by = 5


class TagCreateView(generic.CreateView):
    model = Tag
    fields = [
        "name",
    ]
    success_url = reverse_lazy("todo_list:tag-list")


class TagUpdateView(generic.UpdateView):
    model = Tag
    fields = [
        "name",
    ]
    success_url = reverse_lazy("todo_list:tag-list")


class TagDeleteView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("todo_list:tag-list")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}
    <title>Task List</title>
  {% endblock title %}

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
        integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3">
      {% block sidebar %}
        {% include "includes/sidebar.html" %}
      {% endblock sidebar %}
    </div>
    <div class="col-sm-9">
      {% block content %}
      {% endblock content %}
      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}
    </div>
  </div>
</div>
</body>
</html>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav">
  <li>
    <a href="{% url 'todo_list:task-list' %}">Home page</a>
  </li>
  <li>
    <a href="{% url 'todo_list:tag-list' %}">Tag list</a>
  </li>
</ul>

templates/todo_list/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete tag "{{ tag.name }}" ?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo_list:tag-list' %}" class="btn btn-secondary">No</a>
  </form>
{% endblock %}

templates/todo_list/tag_form.html
{% extends "base.html" %}
{#{% load crispy_forms_filters %}#}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} tag</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/tag_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Tag List
    <a href="{% url 'todo_list:tag-create' %}" class="btn btn-primary link-to-page float-right">
      Add
    </a>
  </h1>

  {% if tag_list %}
    <table class="table">
      <tr>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for tag in tag_list %}
        <tr>
          <td>
            {{ tag.name }}
          </td>
          <td>
            <a href="{% url 'todo_list:tag-update' pk=tag.id %}">
              Update
            </a>
          </td>
          <td>
            <a style="color: red"
               href="{% url 'todo_list:tag-delete' pk=tag.id %}">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no tags</p>
  {% endif %}
{% endblock %}

templates/todo_list/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete task "{{ task.content }}" ?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'todo_list:task-list' %}" class="btn btn-secondary">No</a>
  </form>
{% endblock %}

templates/todo_list/task_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Driver Info:</h1>
  <p>Full name {{ driver.first_name }} {{ driver.last_name }}</p>
  <p>Username: {{ driver.username }}</p>
  <p>License number: {{ driver.license_number }}</p>
  <div class="ml-3">
    <h3>Cars:</h3>
    {% for tag in task.tags.all %}
      <hr>
      <p>{{ tag.name }}</p>
      {% empty %}
      <p>No cars!</p>
    {% endfor %}
  </div>
{% endblock content %}

templates/todo_list/task_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/todo_list/task_list.html
{% extends "base.html" %}

{% block content %}
  <h1>Task List<a href="{% url 'todo_list:task-create' %}" class="btn btn-primary float-right">Create Task</a></h1>
  <br>
  {% if task_list %}
    {% for task in task_list %}
      <li>
        <a href="{% url 'todo_list:task-detail' task.id %}">{{ task.content }}</a> 
        <a href="{% url 'todo_list:task-change-status' pk=task.id %}" style="padding-left: 40px">
          {% if task.is_done %}Done{% else %}Not Done{% endif %}</a>
      <a href="{% url 'todo_list:task-change-status' pk=task.id %}" class="btn btn-primary link-to-page float-right">
          {% if task.is_done %}Complete{% else %}Undo{% endif %}</a>
        <br>
        Created Data: {{ task.datetime }} <br>
        Deadline: {{ task.deadline }} <br>
        
        Tags: 
        {% for tag in task.tags.all %}
          {{ tag }}
        {% endfor %}
        <a href="{% url 'todo_list:task-update' pk=task.id %}">update</a>
        <a href="{% url 'todo_list:task-delete' pk=task.id %}">delete</a>
        <br><br></li>
    {% endfor %}

  {% endif %}
{% endblock content %}